<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUJnteKj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUJnteKj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUJnteKj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUJnteKj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUJnteKj\App_KernelDevDebugContainer([
    'container.build_hash' => 'UJnteKj',
    'container.build_id' => '3dd94e65',
    'container.build_time' => 1652279925,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUJnteKj');
