<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container243NpaD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container243NpaD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container243NpaD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container243NpaD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container243NpaD\App_KernelDevDebugContainer([
    'container.build_hash' => '243NpaD',
    'container.build_id' => '7be68bd9',
    'container.build_time' => 1652270253,
], __DIR__.\DIRECTORY_SEPARATOR.'Container243NpaD');
